name = "Muon"
uuid = "446846d7-b4ce-489d-bf74-72da18fe3629"
authors = ["Danila Bredikhin <danila.bredikhin@embl.de>", "Ilia Kats <i.kats@dkfz-heidelberg.de>"]
version = "0.2.1"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
CompressHashDisplace = "33dc01b2-0ff1-4271-8670-ed883dd4b55b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
CategoricalArrays = "0.9,0.10"
CompressHashDisplace = "0.1.2"
DataFrames = "0.22, 1"
FileIO = "1.6"
HDF5 = "0.16 - 0.99, 1"
Logging = "1.6.7"
OrderedCollections = "1.6"
PooledArrays = "1"
StructArrays = "0.6.4"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[targets]
test = ["Test", "Logging"]
